---
# List of labels common to all resources for this deployment
commonLabels:
  app: hello-world
# List of resources we are going to kustomize
resources:
- deployment.yaml
- service.yaml
- ingress.yaml